# @TODO(aaronhma): Setup tests of C++ code and rocket functionality.
language: python
group: travis_latest # Get the latest travis group
os: linux # Use Linux for testing

# @TODO(aaronhma): ? Use a GPU ?

# Specify the Python 3 version
python:
  - "3.6" # For compatibility reasons.
  - "3.7" # My Python 3 version.
  - "3.8" # Latest Python 3 version.

# Before installation happens
before_install:
  # @TODO(aaronhma): UPDATE
  - python3 --version

# Installation scripts
install:
  # @TODO(aaronhma): Add installation scripts here
  - pip3 install -r requirements.txt # Install from user-defined packages

# Commands to run tests
script:
  # @TODO(aaronhma): UPDATE with test scripts
  # - python3 shared/handlers/error.py
  - python3 --version
  # @TODO(aaronhma, rohan): Setup pytest
  # - pytest

# Setup notifications
notifications:
  # Configure email notifications
  email:
    - aaronhma@gmail.com   # Aaron's Email
    - hi@aaronhma.com      # Aaron's Email
    - rohanf6219@gmail.com # Rohan's Email
    # @TODO(everyone): Add maintainer email addresses to
    # notify them of recent Travis CI builds.
    
